### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by 107295472** [andreytkachenko/libde265-rust#1]
`  error occurred: Command "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX64\\x64\\cl.exe" "-nologo" "-MD" "-Z7" "-Brepro" "-I" "D:\\work\\rust\\heicjpg\\target\\debug\\build\\libde265-sys-d0e2b19e34f09b69\\out\\libde265-1.0.15" "-I" "D:\\work\\rust\\heicjpg\\target\\debug\\build\\libde265-sys-d0e2b19e34f09b69\\out\\libde265-1.0.15\\libde265" "-DHAVE_MALLOC_H=true" "-FoD:\\work\\rust\\heicjpg\\target\\debug\\build\\libde265-sys-d0e2b19e34f09b69\\out\\36ba45dc7cf98034-de265.o" "-c" "D:\\work\\rust\\heicjpg\\target\\debug\\build\\libde265-sys-d0e2b19e34f09b69\\out\\libde265-1.0.15\\libde265\\de265.cc" with args "cl.exe" did not execute successfully (status code exit code: 2).`
`2024-03-15T00:58:53.238228Z ERROR flycheck: Flycheck failed to run the following command: CommandHandle { program: "C:\\Users\\Administrator\\.cargo\\bin\\cargo.exe", arguments: ["clippy", "--workspace", "--message-format=json-diagnostic-rendered-ansi", "--manifest-path", "D:\\work\\rust\\heicjpg\\Cargo.toml", "--all-targets"], current_dir: Some("D:\\work\\rust\\heicjpg") }`

**Comment by andreytkachenko** [comment]
Hi, have no access to Windows. If you can I would glad to see any PR for windows.
